# coding: utf-8

"""
    Appify Hub's Creator API

    The full specification of the service's API used by the project administrators.

    The version of the OpenAPI document: Latest
    Contact: contact@appifyhub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from appifyhub.models.project_type import ProjectType

class TestProjectType(unittest.TestCase):
    """ProjectType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectType(self):
        """Test ProjectType"""
        # inst = ProjectType()

if __name__ == '__main__':
    unittest.main()
