# coding: utf-8

"""
    Appify Hub's Creator API

    The full specification of the service's API used by the project administrators.

    The version of the OpenAPI document: Latest
    Contact: contact@appifyhub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from appifyhub.models.message_template_update_request import MessageTemplateUpdateRequest

class TestMessageTemplateUpdateRequest(unittest.TestCase):
    """MessageTemplateUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessageTemplateUpdateRequest:
        """Test MessageTemplateUpdateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessageTemplateUpdateRequest`
        """
        model = MessageTemplateUpdateRequest()
        if include_optional:
            return MessageTemplateUpdateRequest(
                name = appifyhub.models.settable_request.SettableRequest(
                    value = appifyhub.models.value.value(), ),
                language_tag = appifyhub.models.settable_request.SettableRequest(
                    value = appifyhub.models.value.value(), ),
                title = appifyhub.models.settable_request.SettableRequest(
                    value = appifyhub.models.value.value(), ),
                content = appifyhub.models.settable_request.SettableRequest(
                    value = appifyhub.models.value.value(), ),
                is_html = appifyhub.models.settable_request.SettableRequest(
                    value = appifyhub.models.value.value(), )
            )
        else:
            return MessageTemplateUpdateRequest(
        )
        """

    def testMessageTemplateUpdateRequest(self):
        """Test MessageTemplateUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
