# coding: utf-8

"""
    Appify Hub's Creator API

    The full specification of the service's API used by the project administrators.

    The version of the OpenAPI document: Latest
    Contact: contact@appifyhub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from appifyhub.models.creator_response import CreatorResponse

class TestCreatorResponse(unittest.TestCase):
    """CreatorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatorResponse:
        """Test CreatorResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatorResponse`
        """
        model = CreatorResponse()
        if include_optional:
            return CreatorResponse(
                user_id = '',
                project_id = 56,
                universal_id = '',
                name = '',
                type = 'PERSONAL',
                authority = 'DEFAULT',
                allows_spam = True,
                contact = '',
                contact_type = 'EMAIL',
                birthday = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                company = appifyhub.models.organization_dto.OrganizationDto(
                    name = '', 
                    street = '', 
                    postcode = '', 
                    city = '', 
                    country_code = '', ),
                language_tag = '',
                created_at = '',
                updated_at = ''
            )
        else:
            return CreatorResponse(
                user_id = '',
                project_id = 56,
                universal_id = '',
                type = 'PERSONAL',
                authority = 'DEFAULT',
                allows_spam = True,
                contact_type = 'EMAIL',
                created_at = '',
                updated_at = '',
        )
        """

    def testCreatorResponse(self):
        """Test CreatorResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
