# coding: utf-8

"""
    Appify Hub's Creator API

    The full specification of the service's API used by the project administrators.

    The version of the OpenAPI document: Latest
    Contact: contact@appifyhub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from appifyhub.models.project_create_request import ProjectCreateRequest

class TestProjectCreateRequest(unittest.TestCase):
    """ProjectCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectCreateRequest:
        """Test ProjectCreateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectCreateRequest`
        """
        model = ProjectCreateRequest()
        if include_optional:
            return ProjectCreateRequest(
                type = 'OPENSOURCE',
                user_id_type = 'USERNAME',
                owner_universal_id = '',
                name = '',
                description = '',
                logo_url = '',
                website_url = '',
                language_tag = '',
                max_users = 56,
                anyone_can_search = True,
                requires_signup_codes = True,
                max_signup_codes_per_user = 56,
                mailgun_config = appifyhub.models.mailgun_config_dto.MailgunConfigDto(
                    api_key = '', 
                    domain = '', 
                    sender_name = '', 
                    sender_email = '', ),
                twilio_config = appifyhub.models.twilio_config_dto.TwilioConfigDto(
                    account_sid = '', 
                    auth_token = '', 
                    messaging_service_id = '', 
                    max_price_per_message = 56, 
                    max_retry_attempts = 56, 
                    default_sender_name = '', 
                    default_sender_number = '', ),
                firebase_config = appifyhub.models.firebase_config_dto.FirebaseConfigDto(
                    project_name = '', 
                    service_account_key_json_base64 = '', )
            )
        else:
            return ProjectCreateRequest(
                type = 'OPENSOURCE',
                user_id_type = 'USERNAME',
                owner_universal_id = '',
                name = '',
        )
        """

    def testProjectCreateRequest(self):
        """Test ProjectCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
