# coding: utf-8

"""
    Appify Hub's Creator API

    The full specification of the service's API used by the project administrators.

    The version of the OpenAPI document: Latest
    Contact: contact@appifyhub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from appifyhub.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_authenticate(self) -> None:
        """Test case for authenticate

        Authenticate creator
        """
        pass

    def test_create_api_key(self) -> None:
        """Test case for create_api_key

        Create an API key
        """
        pass


if __name__ == '__main__':
    unittest.main()
