# coding: utf-8

"""
    Appify Hub's Creator API

    The full specification of the service's API used by the project administrators.

    The version of the OpenAPI document: Latest
    Contact: contact@appifyhub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from appifyhub.models.firebase_config_dto import FirebaseConfigDto
from appifyhub.models.mailgun_config_dto import MailgunConfigDto
from appifyhub.models.project_state_response import ProjectStateResponse
from appifyhub.models.project_type import ProjectType
from appifyhub.models.project_user_id_type import ProjectUserIDType
from appifyhub.models.twilio_config_dto import TwilioConfigDto
from typing import Optional, Set
from typing_extensions import Self

class ProjectResponse(BaseModel):
    """
    Operational details of a consumer project
    """ # noqa: E501
    project_id: StrictInt = Field(description="A unique identifier for this consumer project")
    type: ProjectType
    state: ProjectStateResponse
    user_id_type: ProjectUserIDType
    name: StrictStr = Field(description="The name of this consumer project")
    description: Optional[StrictStr] = Field(default=None, description="A short description of this consumer project")
    logo_url: Optional[StrictStr] = Field(default=None, description="The URL to this consumer project's logo")
    website_url: Optional[StrictStr] = Field(default=None, description="The URL to this consumer project's website")
    language_tag: Optional[StrictStr] = Field(default=None, description="The default language of the project (locale represented as in IETF BCP 47)")
    max_users: StrictInt = Field(description="The maximum number of users allowed in the project")
    anyone_can_search: StrictBool = Field(description="Whether any user can search for any other user or not in the project")
    on_hold: StrictBool = Field(description="Whether the consumer project is on hold or not, preventing any actions if true")
    requires_signup_codes: StrictBool = Field(description="Whether this consumer project requires signup codes from users or not")
    max_signup_codes_per_user: StrictInt = Field(description="The maximum number of signup codes that each user of this consumer project can create")
    mailgun_config: Optional[MailgunConfigDto] = None
    twilio_config: Optional[TwilioConfigDto] = None
    firebase_config: Optional[FirebaseConfigDto] = None
    created_at: StrictStr = Field(description="The time the object was created (based on ISO 8601)")
    updated_at: StrictStr = Field(description="The time the object was last updated (based on ISO 8601)")
    __properties: ClassVar[List[str]] = ["project_id", "type", "state", "user_id_type", "name", "description", "logo_url", "website_url", "language_tag", "max_users", "anyone_can_search", "on_hold", "requires_signup_codes", "max_signup_codes_per_user", "mailgun_config", "twilio_config", "firebase_config", "created_at", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProjectResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of state
        if self.state:
            _dict['state'] = self.state.to_dict()
        # override the default output from pydantic by calling `to_dict()` of mailgun_config
        if self.mailgun_config:
            _dict['mailgun_config'] = self.mailgun_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of twilio_config
        if self.twilio_config:
            _dict['twilio_config'] = self.twilio_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of firebase_config
        if self.firebase_config:
            _dict['firebase_config'] = self.firebase_config.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProjectResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "project_id": obj.get("project_id"),
            "type": obj.get("type"),
            "state": ProjectStateResponse.from_dict(obj["state"]) if obj.get("state") is not None else None,
            "user_id_type": obj.get("user_id_type"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "logo_url": obj.get("logo_url"),
            "website_url": obj.get("website_url"),
            "language_tag": obj.get("language_tag"),
            "max_users": obj.get("max_users"),
            "anyone_can_search": obj.get("anyone_can_search"),
            "on_hold": obj.get("on_hold"),
            "requires_signup_codes": obj.get("requires_signup_codes"),
            "max_signup_codes_per_user": obj.get("max_signup_codes_per_user"),
            "mailgun_config": MailgunConfigDto.from_dict(obj["mailgun_config"]) if obj.get("mailgun_config") is not None else None,
            "twilio_config": TwilioConfigDto.from_dict(obj["twilio_config"]) if obj.get("twilio_config") is not None else None,
            "firebase_config": FirebaseConfigDto.from_dict(obj["firebase_config"]) if obj.get("firebase_config") is not None else None,
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


