# coding: utf-8

"""
    Appify Hub's Consumer API

    The full specification of the service's API used by the end-users.

    The version of the OpenAPI document: Latest
    Contact: contact@appifyhub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from appifyhub.models.user_contact_type import UserContactType

class TestUserContactType(unittest.TestCase):
    """UserContactType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserContactType(self):
        """Test UserContactType"""
        # inst = UserContactType()

if __name__ == '__main__':
    unittest.main()
