# coding: utf-8

"""
    Appify Hub's Consumer API

    The full specification of the service's API used by the end-users.

    The version of the OpenAPI document: Latest
    Contact: contact@appifyhub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from appifyhub.models.push_device_type import PushDeviceType

class TestPushDeviceType(unittest.TestCase):
    """PushDeviceType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPushDeviceType(self):
        """Test PushDeviceType"""
        # inst = PushDeviceType()

if __name__ == '__main__':
    unittest.main()
