# coding: utf-8

"""
    Appify Hub's Consumer API

    The full specification of the service's API used by the end-users.

    The version of the OpenAPI document: Latest
    Contact: contact@appifyhub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from appifyhub.models.user_signup_request import UserSignupRequest

class TestUserSignupRequest(unittest.TestCase):
    """UserSignupRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserSignupRequest:
        """Test UserSignupRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserSignupRequest`
        """
        model = UserSignupRequest()
        if include_optional:
            return UserSignupRequest(
                user_id = '',
                raw_signature = '',
                name = '',
                type = 'PERSONAL',
                allows_spam = True,
                contact = '',
                contact_type = 'EMAIL',
                birthday = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                company = appifyhub.models.organization_dto.OrganizationDto(
                    name = '', 
                    street = '', 
                    postcode = '', 
                    city = '', 
                    country_code = '', ),
                language_tag = '',
                signup_code = ''
            )
        else:
            return UserSignupRequest(
                raw_signature = '',
        )
        """

    def testUserSignupRequest(self):
        """Test UserSignupRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
