# coding: utf-8

"""
    Appify Hub's Consumer API

    The full specification of the service's API used by the end-users.

    The version of the OpenAPI document: Latest
    Contact: contact@appifyhub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from appifyhub.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_authenticate(self) -> None:
        """Test case for authenticate

        Authenticate user
        """
        pass

    def test_get_all_tokens(self) -> None:
        """Test case for get_all_tokens

        Get all tokens
        """
        pass

    def test_get_current_token(self) -> None:
        """Test case for get_current_token

        Get the details of the current token
        """
        pass

    def test_refresh(self) -> None:
        """Test case for refresh

        Refresh the current token (get a new one)
        """
        pass

    def test_unauthenticate(self) -> None:
        """Test case for unauthenticate

        Invalidate the current token
        """
        pass

    def test_unauthenticate_tokens(self) -> None:
        """Test case for unauthenticate_tokens

        Invalidate tokens
        """
        pass


if __name__ == '__main__':
    unittest.main()
