# coding: utf-8

"""
    Appify Hub's Creator API

    The full specification of the service's API used by the project administrators.

    The version of the OpenAPI document: Latest
    Contact: contact@appifyhub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ProjectType(str, Enum):
    """
    The type of this consumer project
    """

    """
    allowed enum values
    """
    OPENSOURCE = 'OPENSOURCE'
    COMMERCIAL = 'COMMERCIAL'
    FREE = 'FREE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProjectType from a JSON string"""
        return cls(json.loads(json_str))


