# IMPORTANT: Keep environment variables in sync with application profile configurations

version: '3'

services:
  api:
    build: ../../../
    image: monolith-api-build-h2
    container_name: monolith-api-build-h2
    restart: always
    env_file:
      - ../.env
      - .env
    ports:
      - 80:8080

volumes:
  postgres:
    driver: local
