# IMPORTANT: Keep environment variables in sync with docker configurations

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: "UTC"
  datasource:
    url: "jdbc:${DB_TYPE:postgresql}://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:appifyhub}"
    username: ${POSTGRES_USER:appifyhub}
    password: ${POSTGRES_PASS:appifyhub}

app:
  security:
    jwt:
      keystore-location: ${KEYSTORE_FILE:keystore/debug.jks}
      keystore-password: ${KEYSTORE_PASS:debug!}
      key-alias: ${KEYSTORE_KEY:debug}
      private-key-passphrase: ${KEYSTORE_KEY_PASS:debug!}
      default-expiration-days: ${JWT_EXPIRATION_DAYS:90}
      static-expiration-days: ${API_KEY_EXPIRATION_DAYS:700}
  creator:
    owner:
      name: ${CREATOR_OWNER_NAME:Owner}
      secret: ${CREATOR_OWNER_SECRET:}
      email: ${CREATOR_OWNER_EMAIL:creator@appifyhub.com}
    properties:
      name: ${CREATOR_PROP_PROJECT_NAME:AppifyHub}
  ip2location:
    file: ${IP_2_LOCATION_FILE:}

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}
