spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: "jdbc:h2:mem:ah_db"
  h2:
    console:
      enabled: true

logging:
  level:
    root: ${LOGGING_LEVEL:DEBUG}

otel:
  metric:
    export:
      interval: 5m # longer because it fails by default
  experimental:
    exporter:
      otlp:
        retry:
          enabled: false
  instrumentation:
    annotations:
      enabled: false
    spring-web:
      enabled: false
    spring-webflux:
      enabled: false
    spring-webmvc:
      enabled: false
    log4j-appender:
      enabled: false
    logback-appender:
      enabled: false
    micrometer:
      enabled: false
    kafka:
      enabled: false
