# IMPORTANT: Keep environment variables in sync with docker configurations

server:
  shutdown: graceful
  error:
    whitelabel:
      enabled: false

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: "UTC"
  datasource:
    url: "jdbc:${DB_TYPE:postgresql}://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:appifyhub}"
    username: ${POSTGRES_USER:appifyhub}
    password: ${POSTGRES_PASS:appifyhub}
  lifecycle:
    timeout-per-shutdown-phase: 1m

app:
  security:
    jwt:
      keystore-location: ${KEYSTORE_FILE:keystore/debug.jks}
      keystore-password: ${KEYSTORE_PASS:debug!}
      key-alias: ${KEYSTORE_KEY:debug}
      private-key-passphrase: ${KEYSTORE_KEY_PASS:debug!}
      default-expiration-days: ${JWT_EXPIRATION_DAYS:90}
      static-expiration-days: ${API_KEY_EXPIRATION_DAYS:700}
  creator:
    owner:
      name: ${CREATOR_OWNER_NAME:Owner}
      secret: ${CREATOR_OWNER_SECRET:}
      email: ${CREATOR_OWNER_EMAIL:creator@appifyhub.com}
    properties:
      name: ${CREATOR_PROP_PROJECT_NAME:AppifyHub}
    integrations:
      mailgun:
        api-key: ${MAILGUN_API_KEY:}
        domain: ${MAILGUN_DOMAIN:mailgun.appifyhub.com}
        sender-name: ${MAILGUN_SENDER_NAME:AppifyHub}
        sender-email: ${MAILGUN_SENDER_EMAIL:no-reply@appifyhub.com}
      twilio:
        account-sid: ${TWILIO_ACCOUNT_SID:}
        auth-token: ${TWILIO_AUTH_TOKEN:}
        messaging-service-id: ${TWILIO_MESSAGING_SERVICE_ID:}
        max-price-per-message: ${TWILIO_MAX_PRICE_PER_MESSAGE:2}
        max-retry-attempts: ${TWILIO_MAX_RETRY_ATTEMPTS:2}
        default-sender-name: ${TWILIO_DEFAULT_SENDER_NAME:APPIFY}
        default-sender-number: ${TWILIO_DEFAULT_SENDER:}
      firebase:
        project-name: ${FIREBASE_PROJECT_NAME:Appify Hub}
        service-account-key-base64: ${FIREBASE_SERVICE_ACCOUNT_KEY_BASE_64:}
  ip2location:
    file: ${IP_2_LOCATION_FILE:}

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        # match with below list of endpoints
        include: "info,beans,flyway,health,liquibase,metrics,mappings,prometheus,cors"
  endpoint:
    info:
      enabled: true
      cache:
        time-to-live: "1m"
    beans:
      enabled: true
      cache:
        time-to-live: "1m"
    flyway:
      enabled: true
      cache:
        time-to-live: "1m"
    health:
      enabled: true
      cache:
        time-to-live: "1m"
    liquibase:
      enabled: true
      cache:
        time-to-live: "1m"
    metrics:
      enabled: true
      cache:
        time-to-live: "1m"
    mappings:
      enabled: true
      cache:
        time-to-live: "1m"
    prometheus:
      enabled: true

otel:
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}
  metric:
    export:
      interval: 30s
