# coding: utf-8

"""
    Appify Hub's Consumer API

    The full specification of the service's API used by the end-users.

    The version of the OpenAPI document: Latest
    Contact: contact@appifyhub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Authority(str, Enum):
    """
    The authority level of the user
    """

    """
    allowed enum values
    """
    DEFAULT = 'DEFAULT'
    MODERATOR = 'MODERATOR'
    ADMIN = 'ADMIN'
    OWNER = 'OWNER'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Authority from a JSON string"""
        return cls(json.loads(json_str))


