# IMPORTANT: Keep environment variables in sync with application profile configurations

version: '3'

services:
  db:
    image: postgres:alpine
    container_name: monolith-database-prod-postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432

  api:
    image: docker.pkg.github.com/appifyhub/monolith/service:latest
    container_name: monolith-api-prod-postgres
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 80:8080

volumes:
  postgres:
    driver: local
