# coding: utf-8

"""
    Appify Hub's Consumer API

    The full specification of the service's API used by the end-users.

    The version of the OpenAPI document: Latest
    Contact: contact@appifyhub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class UserContactType(str, Enum):
    """
    The type of the contact channel
    """

    """
    allowed enum values
    """
    EMAIL = 'EMAIL'
    PHONE = 'PHONE'
    CUSTOM = 'CUSTOM'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UserContactType from a JSON string"""
        return cls(json.loads(json_str))


