# coding: utf-8

"""
    Appify Hub's Consumer API

    The full specification of the service's API used by the end-users.

    The version of the OpenAPI document: Latest
    Contact: contact@appifyhub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from appifyhub.api.messaging_api import MessagingApi


class TestMessagingApi(unittest.TestCase):
    """MessagingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MessagingApi()

    def tearDown(self) -> None:
        pass

    def test_add_push_device(self) -> None:
        """Test case for add_push_device

        Add a push device
        """
        pass

    def test_fetch_all_push_devices_for_user(self) -> None:
        """Test case for fetch_all_push_devices_for_user

        Get all push devices
        """
        pass

    def test_fetch_push_device(self) -> None:
        """Test case for fetch_push_device

        Get a push device
        """
        pass

    def test_remove_all_push_devices_for_user(self) -> None:
        """Test case for remove_all_push_devices_for_user

        Remove all push devices
        """
        pass

    def test_remove_push_device(self) -> None:
        """Test case for remove_push_device

        Remove a push device
        """
        pass

    def test_send_message(self) -> None:
        """Test case for send_message

        Send a message to a user
        """
        pass


if __name__ == '__main__':
    unittest.main()
