# coding: utf-8

"""
    Appify Hub's Consumer API

    The full specification of the service's API used by the end-users.

    The version of the OpenAPI document: Latest
    Contact: contact@appifyhub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from appifyhub.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_add_user(self) -> None:
        """Test case for add_user

        Sign up a new user
        """
        pass

    def test_create_signup_code(self) -> None:
        """Test case for create_signup_code

        Create a signup code
        """
        pass

    def test_delete_user(self) -> None:
        """Test case for delete_user

        Delete a user
        """
        pass

    def test_fetch_all_signup_codes_for_user(self) -> None:
        """Test case for fetch_all_signup_codes_for_user

        Get all signup codes
        """
        pass

    def test_get_user(self) -> None:
        """Test case for get_user

        Get a user
        """
        pass

    def test_reset_signature(self) -> None:
        """Test case for reset_signature

        Reset a user's signature
        """
        pass

    def test_search_users(self) -> None:
        """Test case for search_users

        Search the project's users
        """
        pass

    def test_update_authority(self) -> None:
        """Test case for update_authority

        Update a user's authority
        """
        pass

    def test_update_data(self) -> None:
        """Test case for update_data

        Update a user's data
        """
        pass

    def test_update_signature(self) -> None:
        """Test case for update_signature

        Update a user's signature
        """
        pass

    def test_verify_token(self) -> None:
        """Test case for verify_token

        Verify a user's signup token
        """
        pass


if __name__ == '__main__':
    unittest.main()
