openapi: "3.1.0"

info:
  title: Sub-API
  version: Inherited

components:
  schemas:

    # endpoint specs

    Endpoints:
      get:
        summary: Runs the heartbeat check
        operationId: heartbeat
        tags:
          - Health
        responses:
          200:
            $ref: "#/components/schemas/HeartbeatResponseSpec"
          5XX:
            $ref: "../common/api.yaml#/components/schemas/DefaultErrorSpec"

    # response specs

    HeartbeatResponseSpec:
      type: object
      description: Responds with a HeartbeatResponse
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HeartbeatResponse"

    # models

    HeartbeatResponse:
      type: object
      description: A simple heartbeat response
      properties:
        beat_time:
          required: true
          type: string
          format: date-time
          description: The time the heartbeat was triggered (ISO 8601)
          example: "2022-12-24T14:35:05Z"
        request_ip:
          required: false
          type: string
          description: The approximate IP address of the requester
          example: "192.168.178.45"
        request_geo:
          required: false
          type: string
          description: The approximate geographic location of the requester
          example: "Amsterdam, Netherlands"
        version:
          required: true
          type: string
          description: The running version of the service
          example: "1.3.10.beta"
