# coding: utf-8

"""
    Appify Hub's Consumer API

    The full specification of the service's API used by the end-users.

    The version of the OpenAPI document: Latest
    Contact: contact@appifyhub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from appifyhub.models.authority import Authority
from appifyhub.models.organization_dto import OrganizationDto
from appifyhub.models.user_contact_type import UserContactType
from appifyhub.models.user_type import UserType
from typing import Optional, Set
from typing_extensions import Self

class UserResponse(BaseModel):
    """
    The response containing the user details
    """ # noqa: E501
    user_id: StrictStr = Field(description="A unique user identifier within the project. Depending on the project configuration, it can be differently formatted or even auto-generated. ")
    project_id: StrictInt = Field(description="A unique project identifier")
    universal_id: StrictStr = Field(description="The universal ID of the object (user ID and project ID separated by a dollar sign)")
    name: Optional[StrictStr] = Field(default=None, description="The name of the user")
    type: UserType
    authority: Authority
    allows_spam: StrictBool = Field(description="Whether the user allows spam or not")
    contact: Optional[StrictStr] = Field(default=None, description="The contact channel for the user (depends on the contact type)")
    contact_type: Optional[UserContactType] = None
    birthday: Optional[date] = Field(default=None, description="The birthday of the user")
    company: Optional[OrganizationDto] = None
    language_tag: Optional[StrictStr] = Field(default=None, description="The default language of the user (locale represented as in IETF BCP 47)")
    created_at: StrictStr = Field(description="The time the object was created (based on ISO 8601)")
    updated_at: StrictStr = Field(description="The time the object was last updated (based on ISO 8601)")
    __properties: ClassVar[List[str]] = ["user_id", "project_id", "universal_id", "name", "type", "authority", "allows_spam", "contact", "contact_type", "birthday", "company", "language_tag", "created_at", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of company
        if self.company:
            _dict['company'] = self.company.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "user_id": obj.get("user_id"),
            "project_id": obj.get("project_id"),
            "universal_id": obj.get("universal_id"),
            "name": obj.get("name"),
            "type": obj.get("type"),
            "authority": obj.get("authority"),
            "allows_spam": obj.get("allows_spam"),
            "contact": obj.get("contact"),
            "contact_type": obj.get("contact_type"),
            "birthday": obj.get("birthday"),
            "company": OrganizationDto.from_dict(obj["company"]) if obj.get("company") is not None else None,
            "language_tag": obj.get("language_tag"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


