# coding: utf-8

"""
    Appify Hub's Creator API

    The full specification of the service's API used by the project administrators.

    The version of the OpenAPI document: Latest
    Contact: contact@appifyhub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from appifyhub.models.project_response import ProjectResponse

class TestProjectResponse(unittest.TestCase):
    """ProjectResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectResponse:
        """Test ProjectResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectResponse`
        """
        model = ProjectResponse()
        if include_optional:
            return ProjectResponse(
                project_id = 56,
                type = 'OPENSOURCE',
                state = appifyhub.models.project_state_response.ProjectStateResponse(
                    status = 'REVIEW', 
                    usable_features = [
                        appifyhub.models.project_feature_response.ProjectFeatureResponse(
                            name = 'BASIC', 
                            is_required = True, )
                        ], 
                    unusable_features = [
                        appifyhub.models.project_feature_response.ProjectFeatureResponse(
                            name = 'BASIC', 
                            is_required = True, )
                        ], ),
                user_id_type = 'USERNAME',
                name = '',
                description = '',
                logo_url = '',
                website_url = '',
                language_tag = '',
                max_users = 56,
                anyone_can_search = True,
                on_hold = True,
                requires_signup_codes = True,
                max_signup_codes_per_user = 56,
                mailgun_config = appifyhub.models.mailgun_config_dto.MailgunConfigDto(
                    api_key = '', 
                    domain = '', 
                    sender_name = '', 
                    sender_email = '', ),
                twilio_config = appifyhub.models.twilio_config_dto.TwilioConfigDto(
                    account_sid = '', 
                    auth_token = '', 
                    messaging_service_id = '', 
                    max_price_per_message = 56, 
                    max_retry_attempts = 56, 
                    default_sender_name = '', 
                    default_sender_number = '', ),
                firebase_config = appifyhub.models.firebase_config_dto.FirebaseConfigDto(
                    project_name = '', 
                    service_account_key_json_base64 = '', ),
                created_at = '',
                updated_at = ''
            )
        else:
            return ProjectResponse(
                project_id = 56,
                type = 'OPENSOURCE',
                state = appifyhub.models.project_state_response.ProjectStateResponse(
                    status = 'REVIEW', 
                    usable_features = [
                        appifyhub.models.project_feature_response.ProjectFeatureResponse(
                            name = 'BASIC', 
                            is_required = True, )
                        ], 
                    unusable_features = [
                        appifyhub.models.project_feature_response.ProjectFeatureResponse(
                            name = 'BASIC', 
                            is_required = True, )
                        ], ),
                user_id_type = 'USERNAME',
                name = '',
                max_users = 56,
                anyone_can_search = True,
                on_hold = True,
                requires_signup_codes = True,
                max_signup_codes_per_user = 56,
                created_at = '',
                updated_at = '',
        )
        """

    def testProjectResponse(self):
        """Test ProjectResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
