# coding: utf-8

"""
    Appify Hub's Creator API

    The full specification of the service's API used by the project administrators.

    The version of the OpenAPI document: Latest
    Contact: contact@appifyhub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from appifyhub.api.projects_api import ProjectsApi


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectsApi()

    def tearDown(self) -> None:
        pass

    def test_add_project(self) -> None:
        """Test case for add_project

        Creates a new project
        """
        pass

    def test_get_project(self) -> None:
        """Test case for get_project

        Get a project
        """
        pass

    def test_get_projects(self) -> None:
        """Test case for get_projects

        Get all projects
        """
        pass

    def test_remove_project(self) -> None:
        """Test case for remove_project

        Remove a project
        """
        pass

    def test_remove_projects_by_creator(self) -> None:
        """Test case for remove_projects_by_creator

        Remove all projects
        """
        pass

    def test_update_project(self) -> None:
        """Test case for update_project

        Update a project
        """
        pass


if __name__ == '__main__':
    unittest.main()
